# Generated by Django 5.0.2 on 2024-02-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_car_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.BooleanField(default=True, editable=False, verbose_name='Status'),
        ),
    ]
